[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/song/*"
  to = "/.netlify/functions/song-page"
  status = 200

[functions."song-page"]
  included_files = ["reader.html"]
